INSERT INTO FORMULA (from_type, to_type, numerator, denominator, to_offset) VALUES ('km','mi', 5, 8, 0);
INSERT INTO FORMULA (from_type, to_type, numerator, denominator, to_offset) VALUES ('mi','km', 8, 5, 0);
INSERT INTO FORMULA (from_type, to_type, numerator, denominator, to_offset) VALUES ('km','m', 1000, 1, 0);
INSERT INTO FORMULA (from_type, to_type, numerator, denominator, to_offset) VALUES ('m','km', 1, 1000, 0);
INSERT INTO FORMULA (from_type, to_type, numerator, denominator, to_offset) VALUES ('C','F', 9, 5, 32);
INSERT INTO FORMULA (from_type, to_type, numerator, denominator, to_offset) VALUES ('F','C', 5, 9, -32);
INSERT INTO FORMULA (from_type, to_type, numerator, denominator, to_offset) VALUES ('C','K',1, 1, 273.15);
INSERT INTO FORMULA (from_type, to_type, numerator, denominator, to_offset) VALUES ('K','C',1, 1, -273.15);
INSERT INTO FORMULA (from_type, to_type, numerator, denominator, to_offset) VALUES ('kg','lb',2.2046, 1, 0);
INSERT INTO FORMULA (from_type, to_type, numerator, denominator, to_offset) VALUES ('lb','kg',1, 2.2046, 0);