server:
  port: 80
  servlet:
    context-path: /converter

spring:
  flyway:
    url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    password: mypass
    user: myuser
    schemas:
    - "MYSCHEMA"
  datasource:
    url: jdbc:h2:mem:mydb;SCHEMA=MYSCHEMA
    driverClassName: org.h2.Driver
    username: myuser
    password: mypass
  jpa:
    hibernate:
      ddl-auto: none